language: node_js
node_js:
  - "10"
env:
  CXX=g++-4.8
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run test -- --coverage
  - npm run build